sudo: require
language: generic
services: 
  - docker  

before_install:
  - docker build -t nailbiter/for-docker -f Dockerfile.dev .  
script:
  - docker run -e CI=true nailbiter/for-docker npm run test
